### ISSUE TITLE
やったこと

### ISSUE THREAD

**Issue by nonylene** [wass88/isucon8#1]

**Comment by nonylene** [comment]
go 実装

<img width="1183" alt="screen shot 2018-09-15 at 10 10 07" src="https://user-images.githubusercontent.com/7397316/45580736-90b01500-b8cf-11e8-9059-45a466b2fdb6.png">

**Comment by nonylene** [comment]
パスワード: マイページが `isucon:isucon` admin は `admin:admin`

**Comment by nonylene** [comment]
nginx ではなく h2o！！！！！

**Comment by nonylene** [comment]
`isucon-1` が h2o 立っててそれ以外は立ってなさそう

**Comment by nonylene** [comment]
nginx に変える方針

**Comment by nonylene** [comment]
```
sudo systemctl stop firewalld
sudo systemctl disable firewalld
```

**Comment by nonylene** [comment]
```
sudo yum install zsh tmux htop
sudo systemctl stop firewalld
sudo systemctl disable firewalld

function add-user {
  user=$1
  sudo useradd $1
  sudo -u $1 mkdir -p /home/$1/.ssh
  sudo -u $1 chmod 700 /home/$1/.ssh
  sudo -u $1 touch /home/$1/.ssh/authorized_keys
  sudo -u $1 chmod 600 /home/$1/.ssh/authorized_keys
}

add-user nonylene
add-user utgw
add-user wass80
```

**Comment by nonylene** [comment]
```
nonylene ALL=(ALL) NOPASSWD: ALL
utgw ALL=(ALL) NOPASSWD: ALL
wass80 ALL=(ALL) NOPASSWD: ALL
```

**Comment by nonylene** [comment]
hostname 設定した

**Comment by nonylene** [comment]
nginx に載せ替えた

**Comment by nonylene** [comment]
キャッシュするようにした

**Comment by nonylene** [comment]
percona-toolkit を入れた

**Comment by nonylene** [comment]
mysql の conf をとりあえずいい感じにした

**Comment by nonylene** [comment]
slow log

**Comment by wass88** [comment]
access.log を出しました

**Comment by nonylene** [comment]
- nginx が isucon user で動いていたら、 octet-stream かなにかがうまく行かなかったので root で動かす

**Comment by nonylene** [comment]
- サーバーは app  / app / db

**Comment by wass88** [comment]
netdataを眺めていた。
utgwのバックエンドになって論理演算を眺めていた。

**Comment by nonylene** [comment]
mysql に変えたらエラーになった。 mariadb と mysql の互換性は思ったよりなかった

-> slow log が出ないとか

**Comment by wass88** [comment]
アクセスログを眺めた

**Comment by nonylene** [comment]
- smartd を止めた
- max open files とか
- vm の max を変えるかと思ったけど関係なさそうだったのでしなかった
- sysctl は systemd を変えれば十分だった
- grant 、ドメイン名で指定しないとだめだったりした
